spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nawa6
    username: root
    password: QhrtnswoTkddl1!6
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update